
image: openjdk:8-jdk

stages:
  - build
  - deploy

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS: "4333796"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

build:
    tags:
      - android
    script:
      - pwd
      - ./gradlew assemble
    only:
      - master

lintDebug:
  stage: build
  script:
    - pwd
    - ./gradlew tasks
    - ./gradlew assemble
    #- ./gradlew -Pci --console=plain lintDevDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - pwd
    - ./gradlew tasks --all
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
